### ISSUE TITLE
Missing last-update.txt file caused error blocking nightly static gtfs process

### ISSUE THREAD

**Issue by owades** [cal-itp/graas#225]
UpdateTripNames failed due to missing last-update.txt file from Glendora. As a temporary fix I removed Glendora from live-agencies.txt, as they aren't active right now anyway. This won't affect their service, and is a stopgap fix until we prevent their failure from halding the nightly process.

**Comment by unreasonableman** [comment]
@owades Can you add a stack trace and/or repro steps, please?

**Comment by owades** [comment]
@unreasonableman - I was doing the minimum to get things running, and following up now to properly resolve

Here is the error (from [this GH actions run](https://github.com/cal-itp/graas/runs/5797641009?check_suite_focus=true)):
```
Error: Exception in thread "main" gtfu.Fail: java.io.FileNotFoundException: /home/runner/tmp/tuff/glendora-transportation-division/last-update.txt (No such file or directory)
	at gtfu.Util.writeLastModifiedFile(Util.java:386)
	at gtfu.Util.updateCacheIfNeeded(Util.java:436)
	at gtfu.tools.TripListGenerator.generateTripList(TripListGenerator.java:90)
	at gtfu.tools.UpdateTripNames.UpdateTripNames(UpdateTripNames.java:68)
	at gtfu.tools.UpdateTripNames.main(UpdateTripNames.java:131)
Caused by: java.io.FileNotFoundException: /home/runner/tmp/tuff/glendora-transportation-division/last-update.txt (No such file or directory)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:2[98](https://github.com/cal-itp/graas/runs/5797641009?check_suite_focus=true#step:8:98))
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:126)
	at gtfu.Util.writeLastModifiedFile(Util.java:381)
	... 4 more
Error: Process completed with exit code 1.
```
